### ISSUE TITLE
The video's index in the playlist couldn't be parsed

### ISSUE THREAD

**Issue by AestheticSkye** [MicheleCioccarelli/blob-dl#1]
Running `blob-dl "https://www.youtube.com/watch?v=8g4IbKCzemk&list=RD8g4IbKCzemk&index=1&pp=8AUB"` and selecting only the video returns this
```
✔ The url refers to a video in a playlist, which do you want to download? · Only the video

Usage: blob-dl [OPTIONS] [URL]

ERROR: The video's index in the playlist couldn't be parsed, please report this issue to the github page
Type blob-dl --help for a list of all the available options
```

**Comment by MicheleCioccarelli** [comment]
The problem was the url contained text  (in this case `&pp=8AUB`) after `&index=`  which caused some problems with parsing.
The issue has been fixed, and now the code is more robust and can handle these problems.
Thanks for taking the time to report this issue!

**Comment by MicheleCioccarelli** [comment]
I've just published a new release that fixes your issue :)
