### ISSUE TITLE
Resuming download at byte .....

### ISSUE THREAD

**Issue by rh9020** [MicheleCioccarelli/blob-dl#7]
![image](https://github.com/user-attachments/assets/e07d08ab-15bf-4b5f-bb30-ef665712bbd2)
![image](https://github.com/user-attachments/assets/6243fc7f-e98a-4b8d-a377-5853d1bb06c5)

Happened when downloading playlist error occurs for multiple playlist but not all

**Comment by rh9020** [comment]
it did make .part files

**Comment by rh9020** [comment]
should probably include this :)

**Comment by MicheleCioccarelli** [comment]
Was this video from a playlist?
I tried recreating your issue but the command works just fine.
I need to know what playlist it is from because playlist json parsing is probably the issue
let me know :)

**Comment by rh9020** [comment]
Hello, I would rather not share the whole playlist as there are some personal videos in it too.
But i tried the link i send and it also doesnt download.

**Comment by MicheleCioccarelli** [comment]
This was a windows-only problem, since I usually work on a mac I couldn't recreate this at first.
The .part was downloaded because the error was just rendering because I had left a dangerous .expect()

In the newest commit this issue is fixed so you can compile that for a working version of blob-dl.
If you don't have the means to compile blob-dl yourself you can tell me your system specs (Windows version / whether you are on 64 or 32 bits) soI can compile it and send it to you.

**Comment by rh9020** [comment]
Thanks for fixing the issue, but sadly I dont have any idea on how compiling works so I would greatly appreaciate it if you could compile it for me. Im on windows 10 Home 22H2 64 bits, thanks in advance.

**Comment by MicheleCioccarelli** [comment]
Here you go, let me know if this doesn't work
https://file.io/AAnryuHZtySi

**Comment by rh9020** [comment]
Sorry for bothering you again but i clicked the link and it went to a download page but of course google blocked it and when i went to download from other browser the link doesnt work anymore.
![image](https://github.com/user-attachments/assets/e2a82153-c62a-44d4-9435-891b0691bdf4)

(Not me fed up about google liking to block downloads btw)

**Comment by rh9020** [comment]
oh found how to download it anyone google hide it good tho

**Comment by MicheleCioccarelli** [comment]
so is everything fine?

**Comment by rh9020** [comment]
Yes it works great now, thank you so much
